services:
  game-id-fetcher:
    build: 
      context: ./game-id-fetcher
      target: runtime
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - PORT=8000
    ports:
      - "8000:8000" 
    restart: unless-stopped
    networks:
      - john-network

  game-price-fetcher:
    build: 
      context: ./game-price-fetcher
      target: runtime
    environment:
      - PORT=8001
    ports:
      - "8001:8001" 
    restart: unless-stopped
    networks:
      - john-network

  api-gateway:
    build: 
      context: ./api-gateway
      target: runtime
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GAME_ID_SERVICE_URL=http://game-id-fetcher:8000
      - PRICE_SERVICE_URL=http://game-price-fetcher:8001
      - LOG_LEVEL=info
    depends_on:
      - game-id-fetcher
      - game-price-fetcher
    restart: unless-stopped
    networks:
      - john-network

  web:
    build: 
      context: ./web
      target: runtime
    ports:
      - "3000:3000" 
    environment:
      - PORT=3000
    networks:
      - john-network

networks:
  john-network:
    driver: bridge
    name: johns-game-price-network