services:
  price-fetcher:
    build: 
      context: ./price-fetcher
      target: runtime
    environment:
      - API_KEY=${API_KEY}
      - PORT=8000
    ports:
      - "8000:8000" 
    restart: unless-stopped
    networks:
      - john-network

  api-gateway:
    build: 
      context: ./api-gateway
      target: runtime
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PRICE_FETCHER_SERVICE_URL=http://price-fetcher:8000
      - LOG_LEVEL=info
      - REDIS_URL=redis://redis:6379
    depends_on:
      - price-fetcher
      - redis
    restart: unless-stopped
    networks:
      - john-network

  web:
    build: 
      context: ./web
      target: runtime
    ports:
      - "3000:3000" 
    environment:
      - PORT=3000
      - VITE_API_URL=http://localhost:8080 
    depends_on:
      - api-gateway
    networks:
      - john-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - john-network

  tester:
    image: curlimages/curl:latest
    depends_on:
      - api-gateway
      - price-fetcher
      - redis
    networks:
      - john-network
    entrypoint: [ "sleep", "infinity" ] # So you can exec in for debugging, or override in CI

networks:
  john-network:
    driver: bridge
    name: johns-game-price-network