services:
  price-fetcher:
    build: 
      context: ./price-fetcher
      target: runtime
    environment:
      - API_KEY=${API_KEY}
      - PORT=8000
    ports:
      - "8000:8000" 
    restart: unless-stopped
    networks:
      - john-network

  api-gateway:
    build: 
      context: ./api-gateway
      target: runtime
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PRICE_FETCHER_SERVICE_URL=http://price-fetcher:8000
      - LOG_LEVEL=info
    depends_on:
      - price-fetcher
    restart: unless-stopped
    networks:
      - john-network

  web:
    build: 
      context: ./web
      target: runtime
    ports:
      - "3000:3000" 
    environment:
      - PORT=3000
    networks:
      - john-network

networks:
  john-network:
    driver: bridge
    name: johns-game-price-network