services:
  price-fetcher:
    build: 
      context: ./price-fetcher
      target: runtime
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - test-network

  api-gateway:
    build: 
      context: ./api-gateway
      target: runtime
    ports:
      - "8080:8080"
    environment:
      - PRICE_FETCHER_SERVICE_URL=http://price-fetcher:8000
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      price-fetcher:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 20s
    networks:
      - test-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge