services:
  price-fetcher:
    build: 
      context: ./price-fetcher
      target: runtime
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  api-gateway:
    build: 
      context: ./api-gateway
      target: runtime
    ports:
      - "8080:8080"
    environment:
      - PRICE_FETCHER_SERVICE_URL=http://price-fetcher:8000
      - NODE_ENV=production
    depends_on:
      price-fetcher:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s      # Check every 30 seconds
      timeout: 10s       # 10 second timeout
      retries: 3         # Only 3 retries
      start_period: 90s  # Wait 90 seconds before first check
    networks:
      - test-network

networks:
  test-network:
    driver: bridge