version: '3.8'

services:
  game-id-fetcher:
    build: 
      context: ./game-id-fetcher
      target: runtime
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  game-price-fetcher:
    build: 
      context: ./game-price-fetcher
      target: runtime
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: 
      context: ./api-gateway
      target: dev
    ports:
      - "8080:8080"
    environment:
      - GAME_ID_SERVICE_URL=http://game-id-fetcher:8000
      - PRICE_SERVICE_URL=http://game-price-fetcher:8001
      - NODE_ENV=production
    depends_on:
      game-id-fetcher:
        condition: service_healthy
      game-price-fetcher:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5