config:
  clients:
    - url: http://loki:3100/loki/api/v1/push
      tenant_id: admin
  positions:
    filename: /run/promtail/positions.yaml
  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      pipeline_stages:
        - cri: {}
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
      static_configs:
        - targets: ['localhost']
          labels:
            job: varlogs
            __path__: /var/log/containers/*.log