apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: price-fetcher
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: price-fetcher
  endpoints:
    - port: metrics
      interval: 15s