name: Integration Tests

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  integration:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up KinD cluster
        uses: helm/kind-action@v1

      - name: Set up Helm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: azure/setup-helm@v3

      - name: Create price-fetcher-secret
        run: |
          kubectl create secret generic price-fetcher-secret --from-literal=API_KEY=${{ secrets.ISTHEREANYDEAL_API_KEY }} --namespace=default --dry-run=client -o yaml | kubectl apply -f -

      - name: Create Grafana admin secret (placeholder)
        run: |
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic grafana-admin-creds \
            --namespace monitoring \
            --from-literal=admin-user=admin \
            --from-literal=admin-password=admin \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Build Docker images
        run: |
          docker build -t johnsgameprice-api-gateway:latest ./services/api-gateway &
          docker build -t johnsgameprice-price-fetcher:latest ./services/price-fetcher &
          docker build -t johnsgameprice-web:latest ./services/web &
          wait

      - name: Load images into KinD
        run: |
          kind load docker-image johnsgameprice-api-gateway:latest --name chart-testing &
          kind load docker-image johnsgameprice-price-fetcher:latest --name chart-testing &
          kind load docker-image johnsgameprice-web:latest --name chart-testing &
          wait

      - name: Deploy stack
        run: bash scripts/deploy.sh

      - name: Wait for deployments to be ready
        run: |
          set -e

          wait_and_log() {
            local kind="$1"
            local name="$2"
            local ns="$3"
            local timeout="${4:-120s}"

            echo "⏳ Waiting for $kind/$name in namespace $ns to be ready..."
            if ! kubectl rollout status $kind/$name -n $ns --timeout=$timeout; then
              echo "❌ Timeout waiting for $kind/$name in $ns. Fetching pod logs:"
              kubectl get pods -n $ns -o wide
              for pod in $(kubectl get pods -n $ns -l app=${name} -o jsonpath="{.items[*].metadata.name}"); do
                echo "---- Logs for pod $pod ----"
                kubectl logs -n $ns $pod || true
              done
              exit 1
            fi
          }

          wait_and_log deployment api-gateway default 120s
          wait_and_log deployment price-fetcher default 120s
          wait_and_log deployment web default 120s
          wait_and_log deployment grafana monitoring 180s

      - name: Integration Tests
        env:
          USE_KIND: "true"
        run: bash scripts/integration_test.sh

      - name: Show logs on failure
        if: failure()
        run: |
          kubectl get pods -A
          kubectl logs deployment/api-gateway || true
          kubectl logs deployment/price-fetcher || true
          kubectl logs deployment/web || true

      - name: Debug Grafana rollout failure
        if: failure()
        run: |
          kubectl get pods -n monitoring -o wide
          kubectl describe deployment grafana -n monitoring
          kubectl describe pods -n monitoring -l app.kubernetes.io/name=grafana
          for pod in $(kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath="{.items[*].metadata.name}"); do
            echo "---- Logs for pod $pod ----"
            kubectl logs -n monitoring $pod || true
          done

      - name: Clean up
        if: always()
        run: bash scripts/teardown.sh